version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6

commands:
  requirements:
    steps:
      - run:
          name: Install tox
          command: |
            pip install tox

jobs:
  quality:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - requirements
      - run:
          name: Check code quality
          command: |
            tox -e quality
  test-py38-django32:
    docker:
      - image: cimg/python:3.8-browsers
    steps:
      - checkout
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - requirements
      - run:
          name: Run tests
          command: |
            tox -e py38-django32
  test-py38-django42:
    docker:
      - image: cimg/python:3.8-browsers
    steps:
      - checkout
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - requirements
      - run:
          name: Run tests
          command: |
            tox -e py38-django42

workflows:
  version: 2
  main:
    jobs:
      - quality
      - test-py38-django32
      - test-py38-django42
